export const symbolKeys: Record<string, string> = {
  '1. symbol': 'symbol',
  '2. name': 'name',
  '3. type': 'type',
  '4. region': 'region',
  '5. marketOpen': 'marketOpen',
  '6. marketClose': 'marketClose',
  '7. timezone': 'timezone',
  '8. currency': 'currency',
  '9. matchScore': 'matchScore',
};

export const globalQuoteKeys: Record<string, string> = {
  '01. symbol': 'symbol',
  '02. open': 'open',
  '03. high': 'high',
  '04. low': 'low',
  '05. price': 'price',
  '06. volume': 'volume',
  '07. latest trading day': 'latestTradingDay',
  '08. previous close': 'previousClose',
  '09. change': 'change',
  '10. change percent': 'changePercent',
};

export const symbolDetailKeys: Record<string, string> = {
  Symbol: 'symbol',
  AssetType: 'assetType',
  Name: 'name',
  Description: 'description',
  CIK: 'CIK',
  Exchange: 'exchange',
  Currency: 'currency',
  Country: 'country',
  Sector: 'sector',
  Industry: 'industry',
  Address: 'address',
  FullTimeEmployees: 'fullTimeEmployees',
  FiscalYearEnd: 'fiscalYearEnd',
  LatestQuarter: 'latestQuarter',
  MarketCapitalization: 'marketCapitalization',
  EBITDA: 'EBITDA',
  PERatio: 'PERatio',
  PEGRatio: 'PEGRatio',
  BookValue: 'bookValue',
  DividendPerShare: 'dividendPerShare',
  DividendYield: 'dividendYield',
  EPS: 'EPS',
  RevenuePerShareTTM: 'revenuePerShareTTM',
  ProfitMargin: 'profitMargin',
  OperatingMarginTTM: 'operatingMarginTTM',
  ReturnOnAssetsTTM: 'returnOnAssetsTTM',
  ReturnOnEquityTTM: 'returnOnEquityTTM',
  RevenueTTM: 'revenueTTM',
  GrossProfitTTM: 'grossProfitTTM',
  DilutedEPSTTM: 'dilutedEPSTTM',
  QuarterlyEarningsGrowthYOY: 'quarterlyEarningsGrowthYOY',
  QuarterlyRevenueGrowthYOY: 'quarterlyRevenueGrowthYOY',
  AnalystTargetPrice: 'analystTargetPrice',
  TrailingPE: 'trailingPE',
  ForwardPE: 'forwardPE',
  PriceToSalesRatioTTM: 'priceToSalesRatioTTM',
  PriceToBookRatio: 'priceToBookRatio',
  EVToRevenue: 'EVToRevenue',
  EVToEBITDA: 'EVToEBITDA',
  Beta: 'beta',
  '52WeekHigh': 'weekHigh52',
  '52WeekLow': 'weekLow52',
  '50DayMovingAverage': 'dayMovingAverage50',
  '200DayMovingAverage': 'dayMovingAverage200',
  SharesOutstanding: 'sharesOutstanding',
  SharesFloat: 'sharesFloat',
  SharesShort: 'sharesShort',
  SharesShortPriorMonth: 'sharesShortPriorMonth',
  ShortRatio: 'shortRatio',
  ShortPercentOutstanding: 'shortPercentOutstanding',
  ShortPercentFloat: 'shortPercentFloat',
  PercentInsiders: 'percentInsiders',
  PercentInstitutions: 'percentInstitutions',
  ForwardAnnualDividendRate: 'forwardAnnualDividendRate',
  ForwardAnnualDividendYield: 'forwardAnnualDividendYield',
  PayoutRatio: 'payoutRatio',
  DividendDate: 'dividendDate',
  ExDividendDate: 'exDividendDate',
  LastSplitFactor: 'lastSplitFactor',
  LastSplitDate: 'lastSplitDate',
};

export const renameKeys = (
  data: Record<string, string>,
  keyMap: Record<string, string>,
): Record<string, string> => {
  const newData = {};
  Object.keys(data).forEach((key) => {
    newData[keyMap[key]] = data[key];
  });

  return newData;
};
